#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ArenaViewMeTab

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ArenaViewMeTab.ArenaViewMeTab_C
// 0x0008 (0x0330 - 0x0328)
class UArenaViewMeTab_C final : public UFortArenaPersonalViewTab
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_ArenaViewMeTab(int32 EntryPoint);
	void Colorize(const struct FFortTournamentDisplayInfo& ColorInfo);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ArenaViewMeTab_C">();
	}
	static class UArenaViewMeTab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UArenaViewMeTab_C>();
	}
};

}

