#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AthenaMainStatTile

#include "Basic.hpp"

#include "AthenaMainStatTile_classes.hpp"
#include "AthenaMainStatTile_parameters.hpp"


namespace SDK
{

// Function AthenaMainStatTile.AthenaMainStatTile_C.setStatValue
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      StatValueAsText                                        (BlueprintVisible, BlueprintReadOnly, Parm)

void UAthenaMainStatTile_C::setStatValue(const class FText& StatValueAsText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaMainStatTile_C", "setStatValue");

	Params::AthenaMainStatTile_C_setStatValue Parms{};

	Parms.StatValueAsText = std::move(StatValueAsText);

	UObject::ProcessEvent(Func, &Parms);
}

}

