#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AthenaMainStatTile

#include "Basic.hpp"


namespace SDK::Params
{

// Function AthenaMainStatTile.AthenaMainStatTile_C.setStatValue
// 0x0030 (0x0030 - 0x0000)
struct AthenaMainStatTile_C_setStatValue final
{
public:
	class FText                                   StatValueAsText;                                   // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x0018(0x0018)()
};

}

