#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BacchusBoundActionButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "CommonInput_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BacchusBoundActionButton.BacchusBoundActionButton_C
// 0x0020 (0x0C18 - 0x0BF8)
class UBacchusBoundActionButton_C final : public UBacchusBoundActionButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BF8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                ContentBorder;                                     // 0x0C00(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFortMobileImage*                       FortMobileImageInputAction;                        // 0x0C08(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScaleBox*                              InputActionIconScale;                              // 0x0C10(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void UpdateInputActionIconSize();
	void OnUpdateInputAction();
	void Construct();
	void ExecuteUbergraph_BacchusBoundActionButton(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BacchusBoundActionButton_C">();
	}
	static class UBacchusBoundActionButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBacchusBoundActionButton_C>();
	}
};

}

