#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassScreen

#include "Basic.hpp"

#include "BattlePassScreen_classes.hpp"
#include "BattlePassScreen_parameters.hpp"


namespace SDK
{

// Function BattlePassScreen.BattlePassScreen_C.HandleRewardTimelineAnimation
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bAnimateRewardTimeline                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBattlePassScreen_C::HandleRewardTimelineAnimation(bool bAnimateRewardTimeline)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "HandleRewardTimelineAnimation");

	Params::BattlePassScreen_C_HandleRewardTimelineAnimation Parms{};

	Parms.bAnimateRewardTimeline = bAnimateRewardTimeline;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassScreen.BattlePassScreen_C.HandleWatchVideoRequest
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PlayFromDisc                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBattlePassScreen_C::HandleWatchVideoRequest(bool PlayFromDisc)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "HandleWatchVideoRequest");

	Params::BattlePassScreen_C_HandleWatchVideoRequest Parms{};

	Parms.PlayFromDisc = PlayFromDisc;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassScreen.BattlePassScreen_C.HandleViewReward
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInNoReward                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   InNumRewardsToPurchase                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassScreen_C::HandleViewReward(bool bInNoReward, int32 InNumRewardsToPurchase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "HandleViewReward");

	Params::BattlePassScreen_C_HandleViewReward Parms{};

	Parms.bInNoReward = bInNoReward;
	Parms.InNumRewardsToPurchase = InNumRewardsToPurchase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassScreen.BattlePassScreen_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UBattlePassScreen_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassScreen.BattlePassScreen_C.OnRequestViewReward
// (Event, Protected, BlueprintEvent)

void UBattlePassScreen_C::OnRequestViewReward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "OnRequestViewReward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassScreen.BattlePassScreen_C.OnRequestViewRewardComplete
// (Event, Protected, BlueprintEvent)

void UBattlePassScreen_C::OnRequestViewRewardComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "OnRequestViewRewardComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassScreen.BattlePassScreen_C.OnVariantUpdate
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   CurrentIndex                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TotalNumVariants                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassScreen_C::OnVariantUpdate(int32 CurrentIndex, int32 TotalNumVariants)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "OnVariantUpdate");

	Params::BattlePassScreen_C_OnVariantUpdate Parms{};

	Parms.CurrentIndex = CurrentIndex;
	Parms.TotalNumVariants = TotalNumVariants;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassScreen.BattlePassScreen_C.OnBattlePassViewChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// EBattlePassView                         NewView                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassScreen_C::OnBattlePassViewChanged(EBattlePassView NewView)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "OnBattlePassViewChanged");

	Params::BattlePassScreen_C_OnBattlePassViewChanged Parms{};

	Parms.NewView = NewView;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassScreen.BattlePassScreen_C.OnAnimationFinished
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// const class UWidgetAnimation*           Animation                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassScreen_C::OnAnimationFinished(const class UWidgetAnimation* Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "OnAnimationFinished");

	Params::BattlePassScreen_C_OnAnimationFinished Parms{};

	Parms.Animation = Animation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassScreen.BattlePassScreen_C.OnPreviewActionButtonUpdated
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      RowDisplayName                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBattlePassScreen_C::OnPreviewActionButtonUpdated(const class FText& RowDisplayName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "OnPreviewActionButtonUpdated");

	Params::BattlePassScreen_C_OnPreviewActionButtonUpdated Parms{};

	Parms.RowDisplayName = std::move(RowDisplayName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassScreen.BattlePassScreen_C.OnViewReward
// (Event, Protected, BlueprintEvent)
// Parameters:
// const struct FFortRarityItemData&       Rarity                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    bNoReward                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   NumRewardsToPurchase                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UFortItemDefinition*        RewardItem                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassScreen_C::OnViewReward(const struct FFortRarityItemData& Rarity, bool bNoReward, int32 NumRewardsToPurchase, const class UFortItemDefinition* RewardItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "OnViewReward");

	Params::BattlePassScreen_C_OnViewReward Parms{};

	Parms.Rarity = std::move(Rarity);
	Parms.bNoReward = bNoReward;
	Parms.NumRewardsToPurchase = NumRewardsToPurchase;
	Parms.RewardItem = RewardItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassScreen.BattlePassScreen_C.OnWatchVideo
// (Event, Protected, BlueprintEvent)

void UBattlePassScreen_C::OnWatchVideo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "OnWatchVideo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassScreen.BattlePassScreen_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBattlePassScreen_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassScreen.BattlePassScreen_C.ExecuteUbergraph_BattlePassScreen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassScreen_C::ExecuteUbergraph_BattlePassScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassScreen_C", "ExecuteUbergraph_BattlePassScreen");

	Params::BattlePassScreen_C_ExecuteUbergraph_BattlePassScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

