#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassRewardChallenges

#include "Basic.hpp"


namespace SDK::Params
{

// Function BattlePassRewardChallenges.BattlePassRewardChallenges_C.OnInitChallenges
// 0x0018 (0x0018 - 0x0000)
struct BattlePassRewardChallenges_C_OnInitChallenges final
{
public:
	class FText                                   ChallengesTitle;                                   // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};

// Function BattlePassRewardChallenges.BattlePassRewardChallenges_C.OnSetChallengesSwitcher
// 0x0001 (0x0001 - 0x0000)
struct BattlePassRewardChallenges_C_OnSetChallengesSwitcher final
{
public:
	bool                                          bShowChallenges;                                   // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function BattlePassRewardChallenges.BattlePassRewardChallenges_C.ExecuteUbergraph_BattlePassRewardChallenges
// 0x0038 (0x0038 - 0x0000)
struct BattlePassRewardChallenges_C_ExecuteUbergraph_BattlePassRewardChallenges final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class FText                                   K2Node_Event_ChallengesTitle;                      // 0x0008(0x0018)(ConstParm)
	bool                                          K2Node_Event_bShowChallenges;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue_1;       // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

