#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassPagedTrack

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BattlePassPagedTrack.BattlePassPagedTrack_C
// 0x0018 (0x0360 - 0x0348)
class UBattlePassPagedTrack_C final : public UBattlePassRewardPagedTrack
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0348(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Backward;                                          // 0x0350(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Forward;                                           // 0x0358(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void CycleTrackBackward();
	void CycleTrackForward();
	void OnPageChanged(bool bIsForward);
	void ExecuteUbergraph_BattlePassPagedTrack(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BattlePassPagedTrack_C">();
	}
	static class UBattlePassPagedTrack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBattlePassPagedTrack_C>();
	}
};

}

