#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassRewardChallengesEntry

#include "Basic.hpp"

#include "BattlePassRewardChallengesEntry_classes.hpp"
#include "BattlePassRewardChallengesEntry_parameters.hpp"


namespace SDK
{

// Function BattlePassRewardChallengesEntry.BattlePassRewardChallengesEntry_C.OnChallengeComplete
// (Event, Protected, BlueprintEvent)

void UBattlePassRewardChallengesEntry_C::OnChallengeComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassRewardChallengesEntry_C", "OnChallengeComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassRewardChallengesEntry.BattlePassRewardChallengesEntry_C.OnResetChallenge
// (Event, Protected, BlueprintEvent)

void UBattlePassRewardChallengesEntry_C::OnResetChallenge()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassRewardChallengesEntry_C", "OnResetChallenge");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassRewardChallengesEntry.BattlePassRewardChallengesEntry_C.ExecuteUbergraph_BattlePassRewardChallengesEntry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassRewardChallengesEntry_C::ExecuteUbergraph_BattlePassRewardChallengesEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassRewardChallengesEntry_C", "ExecuteUbergraph_BattlePassRewardChallengesEntry");

	Params::BattlePassRewardChallengesEntry_C_ExecuteUbergraph_BattlePassRewardChallengesEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

