#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassNavigator

#include "Basic.hpp"

#include "BattlePassNavigator_classes.hpp"
#include "BattlePassNavigator_parameters.hpp"


namespace SDK
{

// Function BattlePassNavigator.BattlePassNavigator_C.OnTabChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsForwardChange                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBattlePassNavigator_C::OnTabChanged(bool bIsForwardChange)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassNavigator_C", "OnTabChanged");

	Params::BattlePassNavigator_C_OnTabChanged Parms{};

	Parms.bIsForwardChange = bIsForwardChange;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassNavigator.BattlePassNavigator_C.ExecuteUbergraph_BattlePassNavigator
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassNavigator_C::ExecuteUbergraph_BattlePassNavigator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassNavigator_C", "ExecuteUbergraph_BattlePassNavigator");

	Params::BattlePassNavigator_C_ExecuteUbergraph_BattlePassNavigator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

