#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassRewardChallengesEntry

#include "Basic.hpp"


namespace SDK::Params
{

// Function BattlePassRewardChallengesEntry.BattlePassRewardChallengesEntry_C.ExecuteUbergraph_BattlePassRewardChallengesEntry
// 0x0004 (0x0004 - 0x0000)
struct BattlePassRewardChallengesEntry_C_ExecuteUbergraph_BattlePassRewardChallengesEntry final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

