#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassPageReward

#include "Basic.hpp"

#include "BattlePassPageReward_classes.hpp"
#include "BattlePassPageReward_parameters.hpp"


namespace SDK
{

// Function BattlePassPageReward.BattlePassPageReward_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBattlePassPageReward_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "OnMouseLeave");

	Params::BattlePassPageReward_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPageReward.BattlePassPageReward_C.UpdateVisualsToCompletedState
// (Event, Public, BlueprintEvent)

void UBattlePassPageReward_C::UpdateVisualsToCompletedState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "UpdateVisualsToCompletedState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.SetLargeRewardVisuals
// (Event, Public, BlueprintEvent)

void UBattlePassPageReward_C::SetLargeRewardVisuals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "SetLargeRewardVisuals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.ResetToDefault
// (Event, Protected, BlueprintEvent)

void UBattlePassPageReward_C::ResetToDefault()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "ResetToDefault");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.InitForReward
// (Event, Public, BlueprintEvent)
// Parameters:
// const class UFortItemDefinition*        RewardItem                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPageReward_C::InitForReward(const class UFortItemDefinition* RewardItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "InitForReward");

	Params::BattlePassPageReward_C_InitForReward Parms{};

	Parms.RewardItem = RewardItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPageReward.BattlePassPageReward_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UBattlePassPageReward_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBattlePassPageReward_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBattlePassPageReward_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "PreConstruct");

	Params::BattlePassPageReward_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPageReward.BattlePassPageReward_C.BP_OnDeselected
// (Event, Protected, BlueprintEvent)

void UBattlePassPageReward_C::BP_OnDeselected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "BP_OnDeselected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.BP_OnSelected
// (Event, Protected, BlueprintEvent)

void UBattlePassPageReward_C::BP_OnSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "BP_OnSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.OnOverrideIcon
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const TSoftObjectPtr<class UTexture2D>& IconOverride                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, UObjectWrapper, HasGetValueTypeHash)

void UBattlePassPageReward_C::OnOverrideIcon(const TSoftObjectPtr<class UTexture2D>& IconOverride)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "OnOverrideIcon");

	Params::BattlePassPageReward_C_OnOverrideIcon Parms{};

	Parms.IconOverride = IconOverride;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPageReward.BattlePassPageReward_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UBattlePassPageReward_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.ExecuteUbergraph_BattlePassPageReward
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPageReward_C::ExecuteUbergraph_BattlePassPageReward(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "ExecuteUbergraph_BattlePassPageReward");

	Params::BattlePassPageReward_C_ExecuteUbergraph_BattlePassPageReward Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

