#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassPagePipButton

#include "Basic.hpp"

#include "BattlePassPagePipButton_classes.hpp"
#include "BattlePassPagePipButton_parameters.hpp"


namespace SDK
{

// Function BattlePassPagePipButton.BattlePassPagePipButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBattlePassPagePipButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPagePipButton_C", "PreConstruct");

	Params::BattlePassPagePipButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPagePipButton.BattlePassPagePipButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBattlePassPagePipButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPagePipButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPagePipButton.BattlePassPagePipButton_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UBattlePassPagePipButton_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPagePipButton_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPagePipButton.BattlePassPagePipButton_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UBattlePassPagePipButton_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPagePipButton_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPagePipButton.BattlePassPagePipButton_C.BP_OnClicked
// (Event, Protected, BlueprintEvent)

void UBattlePassPagePipButton_C::BP_OnClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPagePipButton_C", "BP_OnClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPagePipButton.BattlePassPagePipButton_C.BP_OnSelected
// (Event, Protected, BlueprintEvent)

void UBattlePassPagePipButton_C::BP_OnSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPagePipButton_C", "BP_OnSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPagePipButton.BattlePassPagePipButton_C.BP_OnDeselected
// (Event, Protected, BlueprintEvent)

void UBattlePassPagePipButton_C::BP_OnDeselected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPagePipButton_C", "BP_OnDeselected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPagePipButton.BattlePassPagePipButton_C.ExecuteUbergraph_BattlePassPagePipButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPagePipButton_C::ExecuteUbergraph_BattlePassPagePipButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPagePipButton_C", "ExecuteUbergraph_BattlePassPagePipButton");

	Params::BattlePassPagePipButton_C_ExecuteUbergraph_BattlePassPagePipButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

