#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BattlePassPagedTrack

#include "Basic.hpp"

#include "BattlePassPagedTrack_classes.hpp"
#include "BattlePassPagedTrack_parameters.hpp"


namespace SDK
{

// Function BattlePassPagedTrack.BattlePassPagedTrack_C.CycleTrackBackward
// (Public, BlueprintCallable, BlueprintEvent)

void UBattlePassPagedTrack_C::CycleTrackBackward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPagedTrack_C", "CycleTrackBackward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPagedTrack.BattlePassPagedTrack_C.CycleTrackForward
// (Public, BlueprintCallable, BlueprintEvent)

void UBattlePassPagedTrack_C::CycleTrackForward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPagedTrack_C", "CycleTrackForward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPagedTrack.BattlePassPagedTrack_C.OnPageChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsForward                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBattlePassPagedTrack_C::OnPageChanged(bool bIsForward)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPagedTrack_C", "OnPageChanged");

	Params::BattlePassPagedTrack_C_OnPageChanged Parms{};

	Parms.bIsForward = bIsForward;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPagedTrack.BattlePassPagedTrack_C.ExecuteUbergraph_BattlePassPagedTrack
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPagedTrack_C::ExecuteUbergraph_BattlePassPagedTrack(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPagedTrack_C", "ExecuteUbergraph_BattlePassPagedTrack");

	Params::BattlePassPagedTrack_C_ExecuteUbergraph_BattlePassPagedTrack Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

