#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_BattlePassNavigatorTabButton

#include "Basic.hpp"

#include "BP_BattlePassNavigatorTabButton_classes.hpp"
#include "BP_BattlePassNavigatorTabButton_parameters.hpp"


namespace SDK
{

// Function BP_BattlePassNavigatorTabButton.BP_BattlePassNavigatorTabButton_C.ToggleSelected
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Selected_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_BattlePassNavigatorTabButton_C::ToggleSelected(bool Selected_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BattlePassNavigatorTabButton_C", "ToggleSelected");

	Params::BP_BattlePassNavigatorTabButton_C_ToggleSelected Parms{};

	Parms.Selected_0 = Selected_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BattlePassNavigatorTabButton.BP_BattlePassNavigatorTabButton_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UBP_BattlePassNavigatorTabButton_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BattlePassNavigatorTabButton_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BattlePassNavigatorTabButton.BP_BattlePassNavigatorTabButton_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UBP_BattlePassNavigatorTabButton_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BattlePassNavigatorTabButton_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BattlePassNavigatorTabButton.BP_BattlePassNavigatorTabButton_C.BP_OnSelected
// (Event, Protected, BlueprintEvent)

void UBP_BattlePassNavigatorTabButton_C::BP_OnSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BattlePassNavigatorTabButton_C", "BP_OnSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BattlePassNavigatorTabButton.BP_BattlePassNavigatorTabButton_C.BP_OnDeselected
// (Event, Protected, BlueprintEvent)

void UBP_BattlePassNavigatorTabButton_C::BP_OnDeselected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BattlePassNavigatorTabButton_C", "BP_OnDeselected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BattlePassNavigatorTabButton.BP_BattlePassNavigatorTabButton_C.ExecuteUbergraph_BP_BattlePassNavigatorTabButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BattlePassNavigatorTabButton_C::ExecuteUbergraph_BP_BattlePassNavigatorTabButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BattlePassNavigatorTabButton_C", "ExecuteUbergraph_BP_BattlePassNavigatorTabButton");

	Params::BP_BattlePassNavigatorTabButton_C_ExecuteUbergraph_BP_BattlePassNavigatorTabButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

