#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ButtonStyle_Clear_Battlepass

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Clear_Battlepass.ButtonStyle-Clear_Battlepass_C
// 0x0000 (0x0570 - 0x0570)
class UButtonStyle_Clear_Battlepass_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Clear_Battlepass_C">();
	}
	static class UButtonStyle_Clear_Battlepass_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_Clear_Battlepass_C>();
	}
};

}

