#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ItemPreviewAnimation

#include "Basic.hpp"

#include "ItemPreviewAnimation_classes.hpp"
#include "ItemPreviewAnimation_parameters.hpp"


namespace SDK
{

// Function ItemPreviewAnimation.ItemPreviewAnimation_C.ExecuteUbergraph_ItemPreviewAnimation
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UItemPreviewAnimation_C::ExecuteUbergraph_ItemPreviewAnimation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemPreviewAnimation_C", "ExecuteUbergraph_ItemPreviewAnimation");

	Params::ItemPreviewAnimation_C_ExecuteUbergraph_ItemPreviewAnimation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemPreviewAnimation.ItemPreviewAnimation_C.OnMontageBlendingOut_Event_HideProps
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimMontage*                     Montage                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInterrupted                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UItemPreviewAnimation_C::OnMontageBlendingOut_Event_HideProps(class UAnimMontage* Montage, bool bInterrupted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemPreviewAnimation_C", "OnMontageBlendingOut_Event_HideProps");

	Params::ItemPreviewAnimation_C_OnMontageBlendingOut_Event_HideProps Parms{};

	Parms.Montage = Montage;
	Parms.bInterrupted = bInterrupted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemPreviewAnimation.ItemPreviewAnimation_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UItemPreviewAnimation_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemPreviewAnimation_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ItemPreviewAnimation.ItemPreviewAnimation_C.OnMontageStarted_Event_HideProps
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimMontage*                     Montage                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UItemPreviewAnimation_C::OnMontageStarted_Event_HideProps(class UAnimMontage* Montage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemPreviewAnimation_C", "OnMontageStarted_Event_HideProps");

	Params::ItemPreviewAnimation_C_OnMontageStarted_Event_HideProps Parms{};

	Parms.Montage = Montage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemPreviewAnimation.ItemPreviewAnimation_C.AnimNotify_LobbySkydive_Gliding
// (BlueprintCallable, BlueprintEvent)

void UItemPreviewAnimation_C::AnimNotify_LobbySkydive_Gliding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemPreviewAnimation_C", "AnimNotify_LobbySkydive_Gliding");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ItemPreviewAnimation.ItemPreviewAnimation_C.AnimNotify_LobbySkydive_Diving
// (BlueprintCallable, BlueprintEvent)

void UItemPreviewAnimation_C::AnimNotify_LobbySkydive_Diving()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemPreviewAnimation_C", "AnimNotify_LobbySkydive_Diving");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ItemPreviewAnimation.ItemPreviewAnimation_C.OnFocusedItemChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// const class UFortItemDefinition*        FocusedItem                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class AFortWeapon*                EquippedWeapon                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class AFortPlayerParachute*       CurrentParachute                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UItemPreviewAnimation_C::OnFocusedItemChanged(const class UFortItemDefinition* FocusedItem, const class AFortWeapon* EquippedWeapon, const class AFortPlayerParachute* CurrentParachute)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemPreviewAnimation_C", "OnFocusedItemChanged");

	Params::ItemPreviewAnimation_C_OnFocusedItemChanged Parms{};

	Parms.FocusedItem = FocusedItem;
	Parms.EquippedWeapon = EquippedWeapon;
	Parms.CurrentParachute = CurrentParachute;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemPreviewAnimation.ItemPreviewAnimation_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UItemPreviewAnimation_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemPreviewAnimation_C", "BlueprintUpdateAnimation");

	Params::ItemPreviewAnimation_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemPreviewAnimation.ItemPreviewAnimation_C.HidePropsForBlend
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimMontage*                     NewMontage                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UItemPreviewAnimation_C::HidePropsForBlend(class UAnimMontage* NewMontage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemPreviewAnimation_C", "HidePropsForBlend");

	Params::ItemPreviewAnimation_C_HidePropsForBlend Parms{};

	Parms.NewMontage = NewMontage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItemPreviewAnimation.ItemPreviewAnimation_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UItemPreviewAnimation_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItemPreviewAnimation_C", "AnimGraph");

	Params::ItemPreviewAnimation_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

