#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SpatialBattlePass

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SpatialBattlePass.SpatialBattlePass_C
// 0x0008 (0x03F0 - 0x03E8)
class USpatialBattlePass_C final : public USpatialBattlePass
{
public:
	class USafeZone*                              SafeZone_1;                                        // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SpatialBattlePass_C">();
	}
	static class USpatialBattlePass_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USpatialBattlePass_C>();
	}
};

}

